[[language]]
name = "sway"
scope = "source.sway"
grammar = "bash"
file-types = [{ glob = "**/sway/config" }, { glob = "**/i3/config" }]
comment-token = "#"
formatter = { command = "/home/blaise/.config/helix/sway-fmt" }
auto-format = true
language-servers = ["efm-sway"]
[language-server.efm-sway]
command = "efm-langserver"
[language-server.efm-sway.config]
documentFormatting = false
languages = { sway = [
  { lintCommand = "sway -c ${INPUT} -C", lintStdin = false, lintFormats = [
    "Error on line %l %m (%f)",
  ] },
] }
[[language]]
auto-format = true
language-servers = ["efm-xml"]
file-types = ["xml", "urdf", "sdf", "xacro"]
name = "xml"
[language-server.efm-xml.config]
documentFormatting = true
languages = { xml = [
  { lintCommand = "xmllint --noout --valid -", lintStdin = true, lintFormats = [
    "%f:%l: %m",
  ] },
  { formatCommand = "xmllint --format -", formatStdin = true },
] }
[language-server.efm-xml]
command = "efm-langserver"
[[language]]
formatter = { command = "rustfmt" }
name = "rust"
[[language]]
auto-format = true
name = "c"
roots = ["compile_commands.json", ".git"]
[[language]]
auto-format = true
formatter = { command = "deno", args = ["fmt", "-", "--ext", "md"] }
language-servers = ["markdown-oxide"]
name = "markdown"
[language-server.markdown-oxide]
command = "markdown-oxide"
[[language]]
auto-format = true
language-servers = ["pylsp"]
name = "python"
[language-server.pylsp]
command = "pylsp"
timeout = 60
[language-server.pylsp.config.pylsp]
skip_token_initialization = true
[language-server.pylsp.config.pylsp.plugins]
preload = { enabled = false }
rope_autoimport = { enabled = false }
[[language]]
formatter = { command = 'prettier', args = ["--parser", "json"] }
name = "json"
[language-server.taplo]
args = ["lsp", "stdio"]
command = "taplo"
[language-server.taplo.config.formatting]
reorder_keys = true
[[language]]
auto-format = true
language-servers = ["taplo"]
name = "toml"
